spring.application.name=demo

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# postgresql stuff
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.username=dev
spring.datasource.password=dev

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 stuff
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always
# to allow connecting to h2 running in docker
#spring.h2.console.settings.web-allow-others=true 



jwt.secret=this-is-a-super-secret-key-that-is-long-enough-for-hs256-algorithm
jwt.expiration=86400000
